apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-many-pvc
  labels:
    app: pvc-demo
    app.kubernetes.io/name: demo-many-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-demo-app
  labels:
    app: pvc-demo
    app.kubernetes.io/name: pvc-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pvc-demo
  template:
    metadata:
      labels:
        app: pvc-demo
    spec:
      containers:
      - name: writer
        image: busybox
        # Dieser Befehl schreibt kontinuierlich in eine Datei den Pod-Namen
        command: ["/bin/sh", "-c", "while true; do echo $(date) - $(hostname) >> /data/shared-log.txt; sleep 5; done"]
        volumeMounts:
        - name: shared-vol
          mountPath: /data
      volumes:
      - name: shared-vol
        persistentVolumeClaim:
          claimName: demo-many-pvc
