apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: k8s-demo-blue-green-httproute
  labels:
    app: k8s-demo-blue-green
    app.kubernetes.io/name: k8s-demo-blue-green-httproute
    app.kubernetes.io/component: server
spec:
  parentRefs:
    - name: nerdapp-work-gateway
      namespace: nerdapp-work
      sectionName: web
    - name: nerdapp-work-gateway
      namespace: nerdapp-work
      sectionName: websecure
  hostnames:
    - blue-green-DOMAIN_PLACEHOLDER
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: k8s-demo-blue-svc
          port: 80
