apiVersion: v1
kind: Secret
metadata:
  name: age-secret
  labels:
    app: secret-demo
    app.kubernetes.io/name: age-secret
type: Opaque
stringData:
  age-key: "AGE-SECRET-KEY-1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ"
