apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-pod
  labels:
    app: secret-demo
    app.kubernetes.io/name: secret-demo-pod
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      env:
        - name: AGE_KEY
          valueFrom:
            secretKeyRef:
              name: age-secret
              key: age-key
#      Geht auch mit envFrom, wie bei ConfigMaps
#      envFrom:
#        - secretRef:
#            name: mein-secret
      volumeMounts:
        - name: secret
          mountPath: "/meine-secrets"
          readOnly: true
        - name: secret-einzeln
          mountPath: "/etc/.neues-dockercfg"
          subPath: ".dockercfg"
          readOnly: true
  volumes:
    - name: secret
      secret:
        secretName: dockercfg-secret
    - name: secret-einzeln
      secret:
        secretName: dockercfg-secret
